name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install and Build Frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        npm test -- --watchAll=false
        
    - name: Install and Build Backend
      working-directory: ./backend
      run: |
        npm ci
        npm run build