name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
        
    - name: Build Backend
      working-directory: ./backend
      run: |
        npm ci
        npm run build
        
    - name: Deploy to Production
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'github-cleaner'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        
    - name: Notify Deployment
      uses: slackapi/slack-github-action@v2.0.0
      with:
        channel-id: 'deployments'
        slack-message: 'Deployment to production completed! :rocket:'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}