name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Frontend Tests
      working-directory: ./frontend
      run: |
        npm ci
        npm run lint
        npm run test:coverage
        npm run test:e2e
        npm run test:a11y
        
    - name: Backend Tests
      working-directory: ./backend
      run: |
        npm ci
        npm run lint
        npm run test:coverage
        npm run test:integration
        
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./frontend/coverage/coverage-final.json,./backend/coverage/coverage-final.json
        fail_ci_if_error: true
        
    - name: Check Coverage Thresholds
      run: |
        FRONTEND_COVERAGE=$(jq '.total.lines.pct' frontend/coverage/coverage-summary.json)
        BACKEND_COVERAGE=$(jq '.total.lines.pct' backend/coverage/coverage-summary.json)
        
        if (( $(echo "$FRONTEND_COVERAGE < 80" | bc -l) )); then
          echo "Frontend coverage ($FRONTEND_COVERAGE%) is below 80%"
          exit 1
        fi
        
        if (( $(echo "$BACKEND_COVERAGE < 80" | bc -l) )); then
          echo "Backend coverage ($BACKEND_COVERAGE%) is below 80%"
          exit 1
        fi
